### ISSUE TITLE
The readme doesn't have any relevant information

### ISSUE THREAD

**Issue by superjohn90** [kaazii/DiscordBot#3]

**Comment by kaazii** [comment]
It now has relevant information. Thank you for your contribution.

**Comment by KevinMKang** [comment]
Do you have plans to support different languages? English may not always be the primary language. Can this be reopened?.

**Comment by superjohn90** [comment]
我是中國人, I think we should reopen

**Comment by KevinMKang** [comment]
我是中國人, I think we should reopen

**Comment by darwintr** [comment]
我是中國人, I think we should reopen

**Comment by kaazii** [comment]
I will be writing this README in english, hindi and gujarati. I do not want  to be asked the question "yo kazi what are you saying" so please ensure you remember this comment.

**Comment by superjohn90** [comment]
Any support for Chinese?

**Comment by kaazii** [comment]
hello,

**Comment by kaazii** [comment]
Relevant information added.
