### ISSUE TITLE
Role Management

### ISSUE THREAD

**Issue by darwintr** [kaazii/DiscordBot#5]
`!joinrole <game>`

`!leaverole <game>`

**Comment by KevinMKang** [comment]
+1

**Comment by superjohn90** [comment]
There are also other options for example, having a dedicated role channel specifically for the bot, and we have reactions.
Whenever you react to the game you want to play, it assigns/un-assigns your role.

Example Carl-bot
![image](https://user-images.githubusercontent.com/22434723/103322958-823d8700-4a0e-11eb-84db-f93d1bcc55ad.png)

**Comment by kaazii** [comment]
Duly noted. Thank you superjohn90.

**Comment by kaazii** [comment]
Side note - should the "Ryerson" tag not be synonymous with "virgin"? Just a thought

**Comment by kaazii** [comment]
Join and Leave commands have been added.
