### ISSUE TITLE
Any plans for Chinese

### ISSUE THREAD

**Issue by MaoZaedong** [kaazii/DiscordBot#6]
请中文

**Comment by kaazii** [comment]
hello,

**Comment by kaazii** [comment]
你好

**Comment by hongyu-wang** [comment]
wo shi zhong guo ren

**Comment by kaazii** [comment]
ok

**Comment by superjohn90** [comment]
This is a duplicate issue, it was already mentioned here https://github.com/kaazii/DiscordBot/issues/3#issuecomment-751540863

**Comment by kaazii** [comment]
Duplicate issue, see above - once again thank you superjohn90.

**Comment by kaazii** [comment]
Added Chinese into the Readme. Thank you.
